project("LuaInterface-MySQL")
	uuid("503e2bf6-3c4c-4673-a48c-245d3e8e09d6")
	kind("SharedLib")
	includedirs({INCLUDE_FOLDER, THIRDPARTY_FOLDER})
	files({"ls_mysql.c", "luasql.c", "luasql.h"})
	vpaths({["Header files"] = "**.h", ["Source files"] = "**.c"})
	links({"LuaInterface", "mysql"})
	targetprefix("")
	targetname("mysql")
	targetsuffix("")

	filter({"system:windows", "platforms:x86"})
		includedirs({"mysql/include"})
		libdirs({"mysql/lib/x86"})

	filter({"system:windows", "platforms:x64"})
		includedirs({"mysql/include"})
		libdirs({"mysql/lib/x64"})

project("LuaInterface-PgSQL")
	uuid("da0e3342-79b9-4a5c-8ed0-2d509f92381c")
	kind("SharedLib")
	includedirs({INCLUDE_FOLDER, THIRDPARTY_FOLDER})
	files({"ls_postgres.c", "luasql.c", "luasql.h"})
	vpaths({["Header files"] = "**.h", ["Source files"] = "**.c"})
	links({"LuaInterface", "pq"})
	targetprefix("")
	targetname("postgres")
	targetsuffix("")

	filter({"system:windows", "platforms:x86"})
		includedirs({"pgsql/include"})
		libdirs({"pgsql/lib/x86"})

	filter({"system:windows", "platforms:x64"})
		includedirs({"pgsql/include"})
		libdirs({"pgsql/lib/x64"})

project("LuaInterface-SQLite")
	uuid("497b93bf-537c-401f-9d7f-56baf3372581")
	kind("SharedLib")
	includedirs({INCLUDE_FOLDER, THIRDPARTY_FOLDER, "sqlite"})
	files({"ls_sqlite3.c", "luasql.c", "luasql.h", "sqlite/*.c", "sqlite/*.h"})
	vpaths({["Header files"] = "**.h", ["Source files"] = "**.c"})
	links({"LuaInterface"})
	targetprefix("")
	targetname("sqlite")
	targetsuffix("")

	filter("system:not windows")
		links({"pthread"})

project("LuaInterface-ODBC")
	uuid("503cabdd-2273-4ae8-a9b8-d5b47b79d670")
	kind("SharedLib")
	includedirs({INCLUDE_FOLDER, THIRDPARTY_FOLDER})
	files({"ls_odbc.c", "luasql.c", "luasql.h"})
	vpaths({["Header files"] = "**.h", ["Source files"] = "**.c"})
	links({"LuaInterface"})
	targetprefix("")
	targetname("odbc")
	targetsuffix("")

	filter("system:windows")
		links({"odbc32"})

	filter("system:not windows")
		defines({"UNIXODBC"})
		links({"odbc"})
