project("LuaInterface-ByteBuffer")
	kind("SharedLib")
	includedirs({"Source", "Modules/ByteBuffer"})
	files({"Modules/ByteBuffer/*.c", "Modules/ByteBuffer/*.cpp", "Modules/ByteBuffer/*.h", "Modules/ByteBuffer/*.hpp"})
	vpaths({["Header files"] = {"**.h", "**.hpp"}, ["Source files"] = {"**.c", "**.cpp"}})
	links({"LuaInterface"})
	targetprefix("")
	targetname("bytebuffer")
	targetsuffix("")