project("LuaInterface-ByteBuffer")
	warnings("Extra")
	kind("SharedLib")
	includedirs({INCLUDE_FOLDER, "./"})
	files({"*.cpp"})
	vpaths({["Source files"] = "**.cpp"})
	links({"LuaInterface"})
	targetprefix("")
	targetname("bytebuffer")
	targetsuffix("")