project("LuaInterface-Pack")
	kind("SharedLib")
	includedirs({INCLUDE_FOLDER, THIRDPARTY_FOLDER})
	files({"*.c"})
	vpaths({["Source files"] = "**.c"})
	links({"LuaInterface"})
	targetprefix("")
	targetname("pack")
	targetsuffix("")