project("LuaInterface-Pack")
	kind("SharedLib")
	includedirs({"Source", LUA_INCLUDES})
	files({"Modules/Pack/*.c", "Modules/Pack/*.cpp", "Modules/Pack/*.h", "Modules/Pack/*.hpp"})
	vpaths({["Header files"] = {"**.h", "**.hpp"}, ["Source files"] = {"**.c", "**.cpp"}})
	links({"LuaInterface"})
	targetprefix("")
	targetname("pack")
	targetsuffix("")