project("LuaInterface-Crypt")
	kind("SharedLib")
	includedirs({INCLUDE_FOLDER, "cryptopp/include"})
	files({"*.cpp"})
	vpaths({["Source files"] = "**.cpp"})
	links({"LuaInterface", "cryptopp"})

	targetprefix("")
	targetname("crypt")
	targetsuffix("")

project("cryptopp")
	kind("StaticLib")
	includedirs({"cryptopp/include/cryptopp", "cryptopp/src"})
	files({"cryptopp/include/cryptopp/*.h", "cryptopp/src/*.cpp"})
	vpaths({["Header files"] = "**.h", ["Source files"] = "**.cpp"})