project("LuaInterface-Socket")
	uuid("d0edb127-edb3-4bd1-9719-0e752acbc7a8")
	kind("SharedLib")
	includedirs({INCLUDE_FOLDER, THIRDPARTY_FOLDER, "./"})
	files({"*.c", "*.h"})
	vpaths({["Header files"] = "**.h", ["Source files"] = "**.c"})
	links({"LuaInterface"})
	targetprefix("")
	targetname("socket")
	targetsuffix("")

	filter("system:windows")
		includedirs({"windows"})
		files({"windows/*.c", "windows/*.h"})
		links({"ws2_32"})

	filter("system:not windows")
		includedirs({"unix"})
		files({"unix/*.c", "unix/*.h"})
