project("LuaInterface-Socket")
	uuid("d0edb127-edb3-4bd1-9719-0e752acbc7a8")
	kind("SharedLib")
	includedirs({INCLUDE_FOLDER, THIRDPARTY_FOLDER, "./"})
	files({"*.c", "*.h"})
	vpaths({["Header files"] = "**.h", ["Source files"] = "**.c"})
	links("LuaInterface")
	targetprefix("")
	targetname("socket.core")
	targetsuffix("")

	filter("system:windows")
		includedirs("windows")
		files({"windows/*.c", "windows/*.h"})
		links("ws2_32")

	filter("system:not windows")
		files({"posix/*.c", "posix/*.h"})
		includedirs("posix")

project("LuaInterface-Mime")
	uuid("ec61a094-e51c-40b7-8be3-a814b847562c")
	kind("SharedLib")
	includedirs({INCLUDE_FOLDER, THIRDPARTY_FOLDER, "./", "mime"})
	files({"mime/*.c", "mime/*.h"})
	vpaths({["Header files"] = "**.h", ["Source files"] = "**.c"})
	links("LuaInterface")
	targetprefix("")
	targetname("mime.core")
	targetsuffix("")

if not os.is("windows") then
	project("LuaInterface-Unix")
		uuid("d3ec60af-109e-49e9-9a7b-901258521b9f")
		kind("SharedLib")
		includedirs({INCLUDE_FOLDER, THIRDPARTY_FOLDER, "./", "unix"})
		files({"unix/*.c", "unix/*.h"})
		vpaths({["Header files"] = "**.h", ["Source files"] = "**.c"})
		links("LuaInterface")
		targetprefix("")
		targetname("unix")
		targetsuffix("")

	project("LuaInterface-Serial")
		uuid("2b7cf180-b88e-4e93-96b8-146e20be86a0")
		kind("SharedLib")
		includedirs({INCLUDE_FOLDER, THIRDPARTY_FOLDER, "./", "serial"})
		files("serial/*.c")
		vpaths({["Source files"] = "**.c"})
		links("LuaInterface")
		targetprefix("")
		targetname("serial")
		targetsuffix("")
end
