project("LuaInterface-Thread")
	warnings("Extra")
	kind("SharedLib")
	includedirs({INCLUDE_FOLDER, THIRDPARTY_FOLDER})
	files({"*.cpp", "*.hpp"})
	vpaths({["Header files"] = "**.hpp", ["Source files"] = "**.cpp"})
	links({"LuaInterface"})
	targetprefix("")
	targetname("thread")
	targetsuffix("")

	configuration("not windows")
		links({"pthread"})