project("LuaInterface-Thread")
	uuid("8c2c6a9b-830b-4fc1-bfb4-a041a3f7ed9d")
	warnings("Extra")
	kind("SharedLib")
	includedirs({INCLUDE_FOLDER, THIRDPARTY_FOLDER})
	files({"*.cpp", "*.hpp"})
	vpaths({["Header files"] = "**.hpp", ["Source files"] = "**.cpp"})
	links("LuaInterface")
	targetprefix("")
	targetname("thread")
	targetsuffix("")

	filter("system:not windows")
		links("pthread")
